language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/jp5169/getmntd

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: getmntd
      on:
          branch: master
