language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/jp5169/getmntd

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: 3506442f-f312-4eca-83cb-08dd59f76501
      app: dev-demo-2021
      on:
          branch: master
